test:
  adapter: 'postgresql'
  host: 'localhost'
  username: 'go'
  password: 'go'
  database: 'app_test'
  encoding: 'UTF8'

qa:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
